$('.video1').click(function() {
  $(this)
    .removeClass('v1')
    .addClass('v1now')
  $('.video2')
    .removeClass('v2now')
    .addClass('v2')
  $('.video1show').css('display', 'block')
  $('.video2show').css('display', 'none')
})

$('.video2').click(function() {
  $(this)
    .removeClass('v2')
    .addClass('v2now')
  $('.video1')
    .removeClass('v1now')
    .addClass('v1')
  $('.video1show').css('display', 'none')
  $('.video2show').css('display', 'block')
})
$('.manhua .m1').click(function() {
  $('.manhua .m1').removeClass('m1now')
  $(this).addClass('m1now')
  var index = $(this).index()
  $('.blBox')
    .children()
    .addClass('none')
  $('.blBox')
    .children()
    .eq(index)
    .removeClass('none')
  $('.bgtu')
    .children()
    .addClass('none')
  $('.bgtu')
    .children()
    .eq(index)
    .removeClass('none')
})
